easy_admin:
   site_name: '<img src="../images/all-blacks-logo-big-data.png" width="80px" height="80px" />'
   design:
     brand_color: '#1ABC9C'
     menu:
       - { entity: 'Torcedor', default: true}
       - Documento
       - label:                'Usuários'
         entity:               User
         icon:                 'users'
         role:   'ROLE_ADMIN'
         route: 'app_action'




   entities:
     Documento:
       class: App\Entity\Documento
       controller: App\Controller\DocumentoController
       form:
         fields:
           - { property: 'documentoFilename', label: 'Arquivo Excel ou XML', type: 'file'}
       list:
         fields:
           - { property: 'documentoFilename', template: '/documento/documentoFile.html.twig' }
         disabled_actions: ['edit']
         actions: ['-edit',{ name: 'delete', icon: 'close', label: 'Excluir' }]

     User:
       templates:
         list: 'admin/user/user_list.html.twig'

       class: App\Entity\User
       controller: App\Controller\UserController
       permissions:
         list: ['ROLE_ADMIN']
         new:  ['ROLE_ADMIN']
         edit: ['ROLE_GRANT_ADMIN']
         delete:  ['ROLE_ADMIN']
       list:
         actions: ['-delete']
       edit:
         role: ['ROLE_SUPER_ADMIN']
         actions: ['-delete']


       form:
         fields:
           - username
           - email
           - lastLogin
           # if administrators are allowed to edit users' passwords and roles, add this:
           - { property: 'plainPassword', type: 'text', type_options: { required: false } }
           - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROL_USUARIO': 'ROL_USER', 'ROL_ADMIN': 'ROLE_ADMIN' } } }




     #        # List the entity class name you want to manage
     Torcedor:
       class: App\Entity\Torcedor
       #label: 'Lista Torcedores'
       edit:
           title: 'Editar Torcedor'
           actions:
             - { name: 'list', icon: 'newspaper-o', label: 'Lista' }
             - { name: 'delete', icon: 'close', label: 'Apagar' }
       new:
           title: 'Novo Torcedor'
           actions:
             - { name: 'list', icon: 'newspaper-o', label: 'Lista' }


       list:
           role: ROLE_USER
           title: 'Lista'
           help: 'Socio Torcedor'
           actions:
             - { name: 'edit', icon: 'pencil' }
             - { name: 'delete', icon: 'close' }
             - { name: 'search', icon: 'search', label: 'Buscar' }
             - { name: 'new', icon: 'plus', label: 'Novo' }
           fields:
             - nome
             - documento
             #- { property: 'documento', format: '%0d' }
             - { property: 'cep', format: '%14d' }
             - { property: 'endereco', label: 'Endereço' }
             - bairro
             - cidade
             - uf
             - { property: 'telefone', type: 'tel' }
             - { property: 'mail',label: 'Email', type: 'email' }
             - ativo


     #Documento:
     #  class: App\Entity\Documento
     #  templates:
     #   edit: 'admin/documento/edit.html.twig'
     #   new: 'admin/documento/new.html.twig'
          # ...
          # these custom templates are only applied to this entity and
          # they override any global template defined in 'design.templates'


#        - App\Entity\Category
#        - App\Entity\User
