swiftmailer:
    transport:   gmail
    username:    markpato@gmail.com
    password:    MintuR2012
    host:        localhost
    port:        465
    encryption:  ssl
    auth-mode:   login

    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

    spool: { type: 'memory' }
